TomatoEnv:
  lamps_on: 0
  lamps_off: 18
  lamps_day_start: -1
  lamps_day_stop: 366
  lamps_off_sun: 400
  lamp_rad_sum_limit: 10
  temp_setpoint_day: 19.5
  temp_setpoint_night: 16.5
  heat_correction: 0
  heat_deadzone: 5
  co2_day: 800
  vent_heat_Pband: 4
  rh_max: 85
  mech_dehumid_Pband: 2
  vent_rh_Pband: 5
  t_vent_off: 1
  vent_cold_Pband: -1
  thScrSpDay: 5
  thScrSpNight: 10
  thScrPband: -1
  thScrDeadZone: 4
  thScrRh: -2
  thScrRhPband: 2
  lampExtraHeat: 2
  blScrExtraRh: 100
  rhMax: 85
  tHeatBand: -1
  co2Band: -100
  useBlScr: 1
