# Description: Configuration file for the Bleiswijk environment
# Always define the general parameters for the base environment
GreenLightEnv:
  weather_data_dir: gl_gym/environments/weather # path to weather data
  location: Amsterdam             # location of the recorded weather data
  data_source: KNMI             # source of the weather data
  nx: 28                          # number of states 
  nd: 10                          # number of weather disturbances
  h: 900                          # [s] time step for the underlying GreenLight solver
  time_interval: 3600             # [s] time interval in between observations
  pred_horizon: 3                 # [days] number of future weather predictions
  n_setpoints: 5                  # number of setpoints we control
  season_length: 60                    # end day of the simulation (16th of December)
  start_train_year: 2010          # start year for training
  end_train_year: 2020            # end year for training
  start_train_day: 250            # start day of the year for training
  end_train_day: 270        # end day of the year for training  training: True           # whether we are training or testing
  # options: Optional[Dict[str Any]] = {} # options for the GreenLight model

DwarfTomatoesObs:
  setpoints_low: [15, 400, 0, 15, 0]      # lower bounds for [temp setpoint,  co2 setpoint, thScr, vent setpoint, lamps]
  setpoints_high: [26, 800, 1, 28, 1]     # upper bounds for [temp setpoint, co2 setpoint, thScr, vent setpoint, lamps]
  reward_function: EconomicReward         # reward function
  eval_options:
    eval_days: [265]                        # days to evaluate the agent on
    eval_years: [2023]                      # year to evaluate the agent on
    location: Bleiswijk                    # location of the greenhouse
    data_source: KASPRO                     # source of the weather data
  selected_obs_mods: [
    IndoorClimateObservations,   
    BasicCropObservations, 
    ActionObservations, 
    ControlObservations, 
    WeatherObservations, 
    WeatherForecastObservations
  ] # observation modules
  obs_mod_kwargs:
    IndoorClimateObservations:
      obs_names: [co2_air, temp_air, pipe_temp, vp_air]
    BasicCropObservations:
      obs_names: [24h_can_temp, c_fruit, t_sum]
    ActionObservations:
      obs_names: [heating_setpoint, co2_setpoint, thr_scr, vent_setpoint, lamp]
    ControlObservations:
      obs_names: [uboil, uco2, uvent, ublscr]
    WeatherObservations:
      obs_names: [glob_rad, temp_out, rh_out, co2_out, wind_speed]
    WeatherForecastObservations:
      obs_names: [glob_rad_pred, temp_out_pred, rh_out_pred, co2_out_pred, wind_speed_pred]
      Np: 1
  reward_kwargs:
    fixed_greenhouse_cost: 15.
    fixed_co2_cost: 0.015
    fixed_lamp_cost: 0.07   # in reality this is multiplied by the max used intensity of the lamps e.g., 200umol/m2/s (we do the same.)
    fixed_screen_cost: 2.   # 1,- per screen
    fixed_spacing_cost: 1.5 # 1,50 per spacing
    off_peak_price: 0.2     # €/kWh
    on_peak_price: 0.3      # €/kWh
    heating_price: 0.09     # €/kWh
    co2_price: 0.3          # €/kg
    fruit_price: 2.0        # €/pot
    max_fruit_weight_pot: 150 # g/pot
    dmfm: 0.078             # dry matter fresh matter ratio
    resolution: hourly      # how often do we get non-zero rewards: hourly or daily

results_columns: [Time, heating_setpoint2, co2_setpoint2, thr_scr2, vent_setpoint2, lamp2,
                    profits, cum_profits, cum_fixed_costs, cum_var_costs, cum_gains, episode
                    ]
