# Description: Configuration file for the Bleiswijk environment
# Always define the general parameters for the base environment
GreenLightEnv:
  weather_data_dir: gl_gym/environments/weather # path to weather data
  location: Amsterdam             # location of the recorded weather data
  data_source: KNMI               # source of the weather data
  num_params: 208                 # number of model parameters
  nx: 28                          # number of states
  nu: 6                           # number of control inputs
  nd: 10                          # number of weather disturbances
  dt: 900                         # [s] time step for the underlying GreenLight solver
  u_min: [0, 0, 0, 0, 0, 0]
  u_max: [1, 1, 1, 1, 1, 1]
  delta_u_max: 0.1                # max change rate in control inputs
  pred_horizon: 0                 # [days] number of future weather predictions
  season_length: 60               # number of days to simulate
  start_train_year: 2010          # start year for training
  end_train_year: 2020            # end year for training
  start_train_day: 40             # start day of the year for training
  end_train_day: 40               # end day of the year for training  training: True           # whether we are training or testing

TomatoEnv:
  reward_function: GreenhouseReward       # reward function to use
  eval_options:
    eval_days: [265]                    # days to evaluate the agent on
    eval_years: [2023]                  # year to evaluate the agent on
    location: Bleiswijk                 # location of the greenhouse
    data_source: KASPRO                 # source of the weather data
 
  observation_modules: [                  # observation modules to use
    IndoorClimateObservations,   
    BasicCropObservations, 
    ControlObservations, 
    WeatherObservations,
    TimeObservations
  ]

  constraints:
    co2_min: 0.         # lower bound on CO2 concentration              [ppm]        0
    co2_max: 1600.        # upper bound on CO2 concentration              [ppm]        2.75e-3
    temp_min: 15.         # lower bound on temperature                    [°C]                    6.5
    temp_max: 34.         # upper bound on temperature                    [°C]                    20
    rh_min: 50.            # lower bound on relative humidity              [#]                     0
    rh_max: 85.          # upper bound on relative humidity               [#]                     70

  reward_params:
    fixed_greenhouse_cost: 15.
    fixed_co2_cost: 0.015
    fixed_lamp_cost: 0.07       # in reality this is multiplied by the max used intensity of the lamps e.g., 200umol/m2/s (we do the same.)
    fixed_screen_cost: 2.       # 1,- per screen
    elec_price: 0.3             # €/kWh
    heating_price: 0.09         # €/kWh
    co2_price: 0.3              # €/kg
    fruit_price: 1.6            # €/kg
    dmfm: 0.065                 # dry matter fresh matter ratio
    pen_weights: [4.e-3, 1.2, 0.4]

# results_columns: [Time, co2_air, co2_top, temp_air, temp_top, can_temp, covin_temp, covex_temp,
#                     thScr_temp, flr_temp, pipe_temp, soil1_temp, soil2_temp, soil3_temp, soil4_temp, soil5_temp, 
#                     vp_air, vp_top, lamp_temp, intlamp_temp, grow_pipe_temp, blscr_temp, 24_can_temp,
#                     cBuf, cleaves, cstem, cFruit, tsum, glob_rad, temp_out, rh_out, co2_out, wind_speed,
#                     heating_setpoint, co2_setpoint, thr_scr, vent_setpoint, lamp,
#                     profits, cum_profits, cum_fixed_costs, cum_var_costs, cum_gains, episode
#                     ]
